### ISSUE TITLE
2020-05-08 Issues

### ISSUE THREAD

**Issue by jeongjaehyeok-edu** [jeongjaehyeok-edu/ks-web#1]
..AppApplication.java
    Line 33~36
        error
Caused by: org.springframework.orm.jpa.JpaSystemException: Unknown integral data type for ids : java.lang.String; nested exception is org.hibernate.id.IdentifierGenerationException: Unknown integral data type for ids : java.lang.String

**Comment by jeongjaehyeok-edu** [comment]
String을 사용한 key설정에 문제가 있는것으로 추정,
entity패키지 내, Person Class를 제외한 모든 Class내 Annotation 수정
  기존     
    @Id
    @GeneratedValue
  수정 
    @Id
    @GeneratedValue(generator="system-uuid")
    @GenericGenerator(name="system-uuid", strategy = "uuid")

컴파일중 오류발생은 사라졌으나, 알 수 없는 값이 출력됨.

**Comment by jeongjaehyeok-edu** [comment]
알 수 없는 값의 정체는 데이터가 아닌 system-uuid 값으로 추정

**Comment by jeongjaehyeok-edu** [comment]
시작부터 어느부분에 문제가 있었는지 확인.
key 값으로 사용 할 
`    private Long id;

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }`
id값 선언과 setter,getter을 선언하지 않아서 key로 사용할 수 없었던 것으로 확인.
@id
@GeneratedValue(generator="system-uuid")
@GenericGenerator(name="system-uuid", strategy = "uuid")
system-uuid로 key를 임의지정? 했던부분 다시 
@id
@GeneratedValue
기존으로 원상복구.

해결완료

**Comment by jeongjaehyeok-edu** [comment]
해결완료

**Comment by jeongjaehyeok-edu** [comment]
에러내용 중 String과 관련한 key값 설정에 대한 문제는 제네릭 속의 Long형 값을 찾을 수 없어서 발생한 것으로 추정?

시작부터 어느부분에 문제가 있었는지 확인.
key 값으로 사용 할
`private Long id;

public Long getId() {
    return id;
}

public void setId(Long id) {
    this.id = id;
}`
기본생성자, id값 선언, setter 및 getter을 작성하지 않아서 key로 사용할 수 없었던 것으로 확인.
@id
@GeneratedValue(generator="system-uuid")
@GenericGenerator(name="system-uuid", strategy = "uuid")
system-uuid로 key를 임의지정? 했던부분 다시
@id
@GeneratedValue
기존으로 원상복구.

해결완료

**Comment by sigmadream** [comment]
에러 사항 잘 찾아서 해결하셨네요. 해당 내용은 나중에 추가로 설명드리겠습니다.

수고하셨습니다.

**Comment by jeongjaehyeok-edu** [comment]
감사합니다!
